language: ruby
rvm:
  - 2.1.5
  - 2.0.0
  - 1.9.3
install: bundle install
before_script:
  - ./setup_tests.sh
  - gem install therubyracer
  - sudo apt-get update -qq
  - sudo apt-get install -qq php5-cli
